In [1]:
pip install yfinance

Requirement already satisfied: yfinance in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (1.7.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (4.14.3)
Requirement already satisfied: curl_cffi>=0.15 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (0.16.3)
Requirement already satisfied: lxml>=4.9.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (6.1.3)
Requirement already satisfied: multitasking>=0.0.7 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (0.0.13)
Requirement already satisfied: numpy>=1.16.5 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (2.4.4)
Requirement already satisfied: pandas>=1.3.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (3.0.2)
Requirement already satisfied: peewee>=3.16.2 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (4.5.1)
Requirement already satisfied: platformdirs>=2.0.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (4.9.4)
Requirement already satisfied: protobuf>=3.19.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (7.36.2)
Requirement already satisfied: pytz>=2022.5 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (2026.3.post1)
Requirement already satisfied: requests>=2.31 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (2.33.1)
Requirement already satisfied: websockets>=13.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from yfinance) (17.1)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=2.0.0 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from curl_cffi>=0.15->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from curl_cffi>=0.15->yfinance) (2026.4.22)
Requirement already satisfied: pycparser in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from cffi>=2.0.0->curl_cffi>=0.15->yfinance) (3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/iku/anaconda3/envs/anaconda3/lib/python3.14/site-packages (from requests>=2.31->yfinance) (2.6.3)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plp
ticker_symbol = "^DJI"
data = yf.download(ticker_symbol, period="max")
data.to_csv('Dow Jones Industrial Average_data.csv')
print("Data downloaded and saved as Dow Jones Industrial Averagedata_data.csv")

[*********************100%***********************]  1 of 1 completed

Data downloaded and saved as Dow Jones Industrial Averagedata_data.csv

In [12]:
df=pd.read_csv("Dow Jones Industrial Average_data.csv")

In [13]:
df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,^DJI,^DJI,^DJI,^DJI,^DJI
1,Date,NaN,NaN,NaN,NaN,NaN
2,1992-01-02,3172.39990234375,3172.6298828125,3139.31005859375,3152.10009765625,23550000
3,1992-01-03,3201.5,3210.639892578125,3165.919921875,3172.39990234375,23620000
4,1992-01-06,3200.10009765625,3213.330078125,3191.860107421875,3201.5,27280000

In [20]:
df.shape

(8754, 6)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8756 entries, 0 to 8755
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   8756 non-null   str
 1   Close   8755 non-null   str
 2   High    8755 non-null   str
 3   Low     8755 non-null   str
 4   Open    8755 non-null   str
 5   Volume  8755 non-null   str
dtypes: str(6)
memory usage: 410.6 KB

In [17]:
df = df.drop([0, 1])

In [19]:
df.head()

,Price,Close,High,Low,Open,Volume
2,1992-01-02,3172.39990234375,3172.6298828125,3139.31005859375,3152.10009765625,23550000
3,1992-01-03,3201.5,3210.639892578125,3165.919921875,3172.39990234375,23620000
4,1992-01-06,3200.10009765625,3213.330078125,3191.860107421875,3201.5,27280000
5,1992-01-07,3204.800048828125,3210.199951171875,3184.47998046875,3200.10009765625,25510000
6,1992-01-08,3203.89990234375,3229.199951171875,3185.820068359375,3204.800048828125,29040000

In [18]:
df.describe()

,Price,Close,High,Low,Open,Volume
count,8754,8754,8754,8754,8754,8754
unique,8754,8651,8633,8635,8630,7851
top,1992-01-02,3292.199951171875,3269.89990234375,3215.340087890625,3292.199951171875,27070000
freq,1,3,3,3,3,5